[build]
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[edge_functions]]
path = "/createStripeCheckout"
function = "createStripeCheckout"

[build.environment]
  NODE_VERSION = "18"
